/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1c1b1b",
        "tertiary": "#555c6a",
        "secondary-container": "#e5e2e1",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#151c27",
        "tertiary-container": "#6e7583",
        "on-surface": "#191c1d",
        "surface-container": "#edeeef",
        "primary-container": "#db322f",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#ffb4ac",
        "on-tertiary-container": "#fefcff",
        "outline-variant": "#e4beb9",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#c0c7d6",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#656464",
        "tertiary-fixed": "#dce2f3",
        "on-surface-variant": "#5b403d",
        "surface": "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "on-primary-container": "#fffbff",
        "on-background": "#191c1d",
        "inverse-surface": "#2e3132",
        "surface-variant": "#e1e3e4",
        "inverse-primary": "#ffb4ac",
        "surface-tint": "#bb171c",
        "on-secondary-fixed-variant": "#474646",
        "surface-dim": "#d9dadb",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "error": "#ba1a1a",
        "primary-fixed": "#ffdad6",
        "on-primary-fixed": "#410002",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "on-error": "#ffffff",
        "secondary": "#5f5e5e",
        "on-tertiary-fixed-variant": "#404754",
        "primary": "#b7131a",
        "secondary-fixed-dim": "#c9c6c5",
        "on-primary-fixed-variant": "#93000d",
        "background": "#f8f9fa",
        "secondary-fixed": "#e5e2e1",
        "outline": "#906f6c",
        "surface-container-highest": "#e1e3e4"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
